-- MySQL Script generated by MySQL Workbench
-- Fri Jul 22 19:18:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema products_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema products_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `products_db` DEFAULT CHARACTER SET utf8 ;
USE `products_db` ;

-- -----------------------------------------------------
-- Table `products_db`.`sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products_db`.`sections` (
  `id_sections` INT NOT NULL AUTO_INCREMENT,
  `name_section` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sections`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products_db`.`products` (
  `id_products` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `section_list` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  `price_without_discount` VARCHAR(45) NULL,
  `promocode_price` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id_products`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products_db`.`sections_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products_db`.`sections_has_products` (
  `sections_id_sections` INT NOT NULL,
  `products_id_products` INT NOT NULL,
  PRIMARY KEY (`sections_id_sections`, `products_id_products`),
  INDEX `fk_sections_has_products_products1_idx` (`products_id_products` ASC) VISIBLE,
  INDEX `fk_sections_has_products_sections_idx` (`sections_id_sections` ASC) VISIBLE,
  CONSTRAINT `fk_sections_has_products_sections`
    FOREIGN KEY (`sections_id_sections`)
    REFERENCES `products_db`.`sections` (`id_sections`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sections_has_products_products1`
    FOREIGN KEY (`products_id_products`)
    REFERENCES `products_db`.`products` (`id_products`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products_db`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products_db`.`images` (
  `id_images` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(45) NULL,
  `extra_images` VARCHAR(45) NULL,
  PRIMARY KEY (`id_images`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products_db`.`product_pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products_db`.`product_pictures` (
  `products_id_products` INT NOT NULL,
  `images_id_images` INT NOT NULL,
  PRIMARY KEY (`products_id_products`, `images_id_images`),
  INDEX `fk_products_has_images_images1_idx` (`images_id_images` ASC) VISIBLE,
  INDEX `fk_products_has_images_products1_idx` (`products_id_products` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_images_products1`
    FOREIGN KEY (`products_id_products`)
    REFERENCES `products_db`.`products` (`id_products`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_images_images1`
    FOREIGN KEY (`images_id_images`)
    REFERENCES `products_db`.`images` (`id_images`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
